### ISSUE TITLE
Runtime error with a tinygo built wasi binary.

### ISSUE THREAD

**Issue by gaboose** [GoogleChromeLabs/asyncify#8]
Tinygo wasm binaries are instrumented with asyncify by default. If you inspect the `wasm.wasm` binary from "Steps to Reproduce The Problem" below with `wasmer inspect wasm.wasm`, you will see the exported `asyncify_...` functions:
```
Type: wasm
Size: 43.6 KB
Imports:
  Functions:
    "wasi_snapshot_preview1"."fd_write": [I32, I32, I32, I32] -> [I32]
    "env"."main.add": [I32, I32, I32, I32] -> [I32]
    "env"."main.result": [I32, I32, I32] -> []
  Memories:
  Tables:
  Globals:
Exports:
  Functions:
    "malloc": [I32] -> [I32]
    "free": [I32] -> []
    "calloc": [I32, I32] -> [I32]
    "realloc": [I32, I32] -> [I32]
    "posix_memalign": [I32, I32, I32] -> [I32]
    "aligned_alloc": [I32, I32] -> [I32]
    "malloc_usable_size": [I32] -> [I32]
    "_start": [] -> []
    "asyncify_start_unwind": [I32] -> []
    "asyncify_stop_unwind": [] -> []
    "asyncify_start_rewind": [I32] -> []
    "asyncify_stop_rewind": [] -> []
    "asyncify_get_state": [] -> [I32]
  Memories:
    "memory": not shared (2 pages..)
  Tables:
  Globals:
```

When I try running it with this library though, I get what looks like a go panic: `panic: runtime error: deadlocked: no event source` is printed to stdout, and the interpreter throws a runtime error.

I'm not really sure if it's the fault with this library, tinygo or my attempt to put these two together. My use case is to run `wasi` compiled go code on the browser where `fd_write` and `fd_read` can return asynchronously. I'm trying to write a library where stdin and stdout are exposed as [ReadableStreams](https://developer.mozilla.org/en-US/docs/Web/API/ReadableStream), and it would be amazing if inside `fd_read` an async call like `let chunk = await stdin.getReader().read()` could work.

## Expected Behavior
I get this if I remove the `async` keywords from the lines `"main.add": async function(x, y) {` and `"main.result": async function(z) {` lines, then everything works fine.

![shot-2022-01-23_18-58-55](https://user-images.githubusercontent.com/1573047/150691555-1df7a212-421f-4922-ac05-d6769909ed14.jpg)

## Actual Behavior
This is what I actually get using async imported functions.

![shot-2022-01-23_19-26-29](https://user-images.githubusercontent.com/1573047/150692534-ebed3f57-edce-4fe6-8c86-1b679d25ad79.jpg)

## Steps to Reproduce the Problem

1. Create `main.go`:
```go
package main

func main() {
	result(add(2, 2))
}

func add(x, y int) int
func result(z int)
```
2. Create `index.html`:
```html
<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8"/>
</head>
<body>
<script type="module">
import * as Asyncify from 'https://unpkg.com/asyncify-wasm?module';

async function main() {
    let { instance } = await Asyncify.instantiateStreaming(fetch("/wasm.wasm"), {
        wasi_snapshot_preview1: {
            fd_write: function(fd, iovsPtr, iovsLen, nwrittenPtr){
                let fullArr = [];
                let view = new DataView(instance.exports.memory.buffer);
                for (let i = 0; i < iovsLen; i++) {
                    let iovPtr = iovsPtr + i * 8;
                    let bufPtr = view.getUint32(iovPtr, true);
                    var bufLen = view.getUint32(iovPtr + 4, true);
                    let arr = new Uint8Array(view.buffer, bufPtr, bufLen);
                    for (let j = 0; j < arr.byteLength; j++) {
                        fullArr.push(arr[j]);
                    }
                }
                console.log("fd_write:", fd, String.fromCharCode.apply(null, fullArr));
                view.setUint32(nwrittenPtr, fullArr.length, true);
                return 0;
            },
        },
        env: {
            "main.add": async function(x, y) {
                console.log("add:", x, y);
                return x + y
            },
            "main.result": async function(z) {
                console.log("result:", z);
            }
        }
    });

    instance.exports._start();
}

main();
</script>
</body>
</html>
```
3. Compile `main.go` to a wasi target: ` tinygo build -o wasm.wasm -target wasi main.go`.
4. Serve directory on http: `python3 -m http.server`.
5. Go to localhost:8000, open browser console.

## Specifications

- Version: https://unpkg.com/asyncify-wasm@1.2.1/dist/asyncify.mjs?module
- Platform: Google Chrome Version 97.0.4692.99 (Official Build) (64-bit)
